Step3
any1978/manyo_kadai pull request #4
Opened 2020-05-01 02:29 UTC by any1978

rspec test中

2020-05-03 11:49 UTC, any1978 commented
●タスクに対して、終了期限を登録。
●一覧画面で、終了期限でソート。
●ステータス（未着手・着手中・完了）を登録。
●一覧画面でタイトルとステータスの両方で絞り込み検索。
●検索インデックスを貼る。
●タスクに対して、優先順位（高中低）を登録。
●優先順位で高い順にソートする。
●KaminariというGemを使って一覧画面にページネーションを追加。
●Bootstrapを導入して、これまで作成したアプリにデザインを当てる。
●GitHub上でPRを作成してレビューしてもらう。
●終了期限のテストをSystem Specで追記。
●バリデーションのModel Specを追加。
●検索ロジックのModel Specを追加。
●ステータスのテストをSystem Specで追記。
●Bootstrap導入後のテストが落ちないか確認。
●デバック・Kaminari・bootstrap・jquery-rails以外のgemは追加していないこと。

2020-05-03 12:21 UTC, yuji91 requested changes

2020-05-03 12:21 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +      # @tasks = Task.except(:end_date)
こちら不要なコメントでしたら削除をお願いします。

2020-05-03 12:21 UTC, yuji91 commented on app/controllers/tasks_controller.rb
> +    # binding.irb
不要なコメントが残っています。

2020-05-03 12:21 UTC, yuji91 commented on spec/models/task_spec.rb
> +      FactoryBot.create(:task, name: "task1", description: '失敗テスト1', end_date: '2020-05-18 00:00:00 +0900', status: '着手中', priority: 0)
設定ファイルに追記することで`FactoryBot.`という記載は省略できます。

2020-05-03 12:58 UTC, any1978 commented
お疲れ様です。
コミットID 「107e6e8」で修正しました。よろしくお願い致します。

2020-05-03 12:59 UTC, any1978 commented
お疲れ様です。
コミットID 「107e6e8」で修正しました。よろしくお願い致します。

2020-05-04 02:38 UTC, yuji91 commented
コミットIDは下記の様に半角スペースで囲むとリンクになります。
107e6e8 で修正

また、新しくコメントを追加するより下記のコメント自体に返答した方が見やすいです。
https://github.com/any1978/manyo_kadai/pull/4#discussion_r419095659

2020-05-04 02:44 UTC, any1978 commented
> コミットIDは下記の様に半角スペースで囲むとリンクになります。
> [107e6e8](https://github.com/any1978/manyo_kadai/commit/107e6e89560243d95e789e56956db7fc82953c37) で修正
> 
> また、新しくコメントを追加するより下記のコメント自体に返答した方が見やすいです。
> [#4 (comment)](https://github.com/any1978/manyo_kadai/pull/4#discussion_r419095659)

上記の件 承知しました。ありがとうございます。

2020-05-04 02:52 UTC, any1978 commented
> コミットIDは下記の様に半角スペースで囲むとリンクになります。
> [107e6e8](https://github.com/any1978/manyo_kadai/commit/107e6e89560243d95e789e56956db7fc82953c37) で修正
> 
> また、新しくコメントを追加するより下記のコメント自体に返答した方が見やすいです。
> [#4 (comment)](https://github.com/any1978/manyo_kadai/pull/4#discussion_r419095659)

上記の件承知しました。ありがとうございます。

2020-05-05 01:18 UTC, yuji91 commented
分かりづらくてすみません。下記のように指摘事項のコメント自体に返信する形を想定しています。
![image](https://user-images.githubusercontent.com/28836274/81027738-c7c6a600-8eb9-11ea-984f-b6e876163e66.png)

2020-05-05 01:24 UTC, any1978 commented on spec/models/task_spec.rb
> +      FactoryBot.create(:task, name: "task1", description: '失敗テスト1', end_date: '2020-05-18 00:00:00 +0900', status: '着手中', priority: 0)
800f0f0 で修正しました。宜しくお願いいたします。宜しくお願いいたします。

2020-05-05 01:31 UTC, merged